sonar.projectKey=tonetest
sonar.projectName=tonetest
sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.typescript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts